/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TcggameRouteImport } from './routes/tcggame'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdmindevRouteImport } from './routes/admindev'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TcggameIndexRouteImport } from './routes/tcggame.index'
import { Route as AdmindevIndexRouteImport } from './routes/admindev.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TcggameTradeRouteImport } from './routes/tcggame.trade'
import { Route as TcggameRankingRouteImport } from './routes/tcggame.ranking'
import { Route as TcggameProfile_Char123nameChar125RouteImport } from './routes/tcggame.profile_{$name}'
import { Route as TcggameDuelsRouteImport } from './routes/tcggame.duels'
import { Route as TcggameDecksRouteImport } from './routes/tcggame.decks'
import { Route as TcggameDailyRouteImport } from './routes/tcggame.daily'
import { Route as TcggameCraftRouteImport } from './routes/tcggame.craft'
import { Route as TcggameCardsRouteImport } from './routes/tcggame.cards'
import { Route as TcggameAchievementsRouteImport } from './routes/tcggame.achievements'
import { Route as AdmindevWoptcgRouteImport } from './routes/admindev.woptcg'
import { Route as AdmindevRequestsRouteImport } from './routes/admindev.requests'
import { Route as AdmindevItemsRouteImport } from './routes/admindev.items'
import { Route as AdminWoptcgRouteImport } from './routes/admin.woptcg'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AuthenticatedTripulacaoRouteImport } from './routes/_authenticated/tripulacao'
import { Route as AuthenticatedPetsRouteImport } from './routes/_authenticated/pets'
import { Route as AuthenticatedNavioRouteImport } from './routes/_authenticated/navio'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdmindevWoptcgIndexRouteImport } from './routes/admindev.woptcg.index'
import { Route as AdmindevNpcsIndexRouteImport } from './routes/admindev.npcs.index'
import { Route as AdmindevCrewsIndexRouteImport } from './routes/admindev.crews.index'
import { Route as AdminWoptcgIndexRouteImport } from './routes/admin.woptcg.index'
import { Route as AdminNpcsIndexRouteImport } from './routes/admin.npcs.index'
import { Route as AdminCrewsIndexRouteImport } from './routes/admin.crews.index'
import { Route as AuthenticatedPersonagensIndexRouteImport } from './routes/_authenticated/personagens.index'
import { Route as AdmindevWoptcgJogadoresRouteImport } from './routes/admindev.woptcg.jogadores'
import { Route as AdmindevWoptcgCartasRouteImport } from './routes/admindev.woptcg.cartas'
import { Route as AdmindevWoptcgBannerdueloRouteImport } from './routes/admindev.woptcg.bannerduelo'
import { Route as AdmindevPlayersIdRouteImport } from './routes/admindev.players.$id'
import { Route as AdmindevNpcsIdRouteImport } from './routes/admindev.npcs.$id'
import { Route as AdmindevCrewsIdRouteImport } from './routes/admindev.crews.$id'
import { Route as AdminWoptcgJogadoresRouteImport } from './routes/admin.woptcg.jogadores'
import { Route as AdminWoptcgCartasRouteImport } from './routes/admin.woptcg.cartas'
import { Route as AdminWoptcgBannerdueloRouteImport } from './routes/admin.woptcg.bannerduelo'
import { Route as AdminPlayersIdRouteImport } from './routes/admin.players.$id'
import { Route as AdminNpcsIdRouteImport } from './routes/admin.npcs.$id'
import { Route as AdminCrewsIdRouteImport } from './routes/admin.crews.$id'
import { Route as AuthenticatedPersonagensIdRouteImport } from './routes/_authenticated/personagens.$id'
import { Route as AdmindevWoptcgJogadorUserIdRouteImport } from './routes/admindev.woptcg.jogador.$userId'
import { Route as AdminWoptcgJogadorUserIdRouteImport } from './routes/admin.woptcg.jogador.$userId'

const TcggameRoute = TcggameRouteImport.update({
  id: '/tcggame',
  path: '/tcggame',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindevRoute = AdmindevRouteImport.update({
  id: '/admindev',
  path: '/admindev',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TcggameIndexRoute = TcggameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TcggameRoute,
} as any)
const AdmindevIndexRoute = AdmindevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TcggameTradeRoute = TcggameTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => TcggameRoute,
} as any)
const TcggameRankingRoute = TcggameRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => TcggameRoute,
} as any)
const TcggameProfile_Char123nameChar125Route =
  TcggameProfile_Char123nameChar125RouteImport.update({
    id: '/profile_{$name}',
    path: '/profile_{$name}',
    getParentRoute: () => TcggameRoute,
  } as any)
const TcggameDuelsRoute = TcggameDuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => TcggameRoute,
} as any)
const TcggameDecksRoute = TcggameDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => TcggameRoute,
} as any)
const TcggameDailyRoute = TcggameDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => TcggameRoute,
} as any)
const TcggameCraftRoute = TcggameCraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => TcggameRoute,
} as any)
const TcggameCardsRoute = TcggameCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => TcggameRoute,
} as any)
const TcggameAchievementsRoute = TcggameAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => TcggameRoute,
} as any)
const AdmindevWoptcgRoute = AdmindevWoptcgRouteImport.update({
  id: '/woptcg',
  path: '/woptcg',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdmindevRequestsRoute = AdmindevRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdmindevItemsRoute = AdmindevItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdminWoptcgRoute = AdminWoptcgRouteImport.update({
  id: '/woptcg',
  path: '/woptcg',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTripulacaoRoute = AuthenticatedTripulacaoRouteImport.update({
  id: '/tripulacao',
  path: '/tripulacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPetsRoute = AuthenticatedPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNavioRoute = AuthenticatedNavioRouteImport.update({
  id: '/navio',
  path: '/navio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdmindevWoptcgIndexRoute = AdmindevWoptcgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdmindevWoptcgRoute,
} as any)
const AdmindevNpcsIndexRoute = AdmindevNpcsIndexRouteImport.update({
  id: '/npcs/',
  path: '/npcs/',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdmindevCrewsIndexRoute = AdmindevCrewsIndexRouteImport.update({
  id: '/crews/',
  path: '/crews/',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdminWoptcgIndexRoute = AdminWoptcgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWoptcgRoute,
} as any)
const AdminNpcsIndexRoute = AdminNpcsIndexRouteImport.update({
  id: '/npcs/',
  path: '/npcs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrewsIndexRoute = AdminCrewsIndexRouteImport.update({
  id: '/crews/',
  path: '/crews/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPersonagensIndexRoute =
  AuthenticatedPersonagensIndexRouteImport.update({
    id: '/personagens/',
    path: '/personagens/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdmindevWoptcgJogadoresRoute = AdmindevWoptcgJogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => AdmindevWoptcgRoute,
} as any)
const AdmindevWoptcgCartasRoute = AdmindevWoptcgCartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => AdmindevWoptcgRoute,
} as any)
const AdmindevWoptcgBannerdueloRoute =
  AdmindevWoptcgBannerdueloRouteImport.update({
    id: '/bannerduelo',
    path: '/bannerduelo',
    getParentRoute: () => AdmindevWoptcgRoute,
  } as any)
const AdmindevPlayersIdRoute = AdmindevPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdmindevNpcsIdRoute = AdmindevNpcsIdRouteImport.update({
  id: '/npcs/$id',
  path: '/npcs/$id',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdmindevCrewsIdRoute = AdmindevCrewsIdRouteImport.update({
  id: '/crews/$id',
  path: '/crews/$id',
  getParentRoute: () => AdmindevRoute,
} as any)
const AdminWoptcgJogadoresRoute = AdminWoptcgJogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => AdminWoptcgRoute,
} as any)
const AdminWoptcgCartasRoute = AdminWoptcgCartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => AdminWoptcgRoute,
} as any)
const AdminWoptcgBannerdueloRoute = AdminWoptcgBannerdueloRouteImport.update({
  id: '/bannerduelo',
  path: '/bannerduelo',
  getParentRoute: () => AdminWoptcgRoute,
} as any)
const AdminPlayersIdRoute = AdminPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNpcsIdRoute = AdminNpcsIdRouteImport.update({
  id: '/npcs/$id',
  path: '/npcs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrewsIdRoute = AdminCrewsIdRouteImport.update({
  id: '/crews/$id',
  path: '/crews/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPersonagensIdRoute =
  AuthenticatedPersonagensIdRouteImport.update({
    id: '/personagens/$id',
    path: '/personagens/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdmindevWoptcgJogadorUserIdRoute =
  AdmindevWoptcgJogadorUserIdRouteImport.update({
    id: '/jogador/$userId',
    path: '/jogador/$userId',
    getParentRoute: () => AdmindevWoptcgRoute,
  } as any)
const AdminWoptcgJogadorUserIdRoute =
  AdminWoptcgJogadorUserIdRouteImport.update({
    id: '/jogador/$userId',
    path: '/jogador/$userId',
    getParentRoute: () => AdminWoptcgRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admindev': typeof AdmindevRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/tcggame': typeof TcggameRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/navio': typeof AuthenticatedNavioRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/tripulacao': typeof AuthenticatedTripulacaoRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/woptcg': typeof AdminWoptcgRouteWithChildren
  '/admindev/items': typeof AdmindevItemsRoute
  '/admindev/requests': typeof AdmindevRequestsRoute
  '/admindev/woptcg': typeof AdmindevWoptcgRouteWithChildren
  '/tcggame/achievements': typeof TcggameAchievementsRoute
  '/tcggame/cards': typeof TcggameCardsRoute
  '/tcggame/craft': typeof TcggameCraftRoute
  '/tcggame/daily': typeof TcggameDailyRoute
  '/tcggame/decks': typeof TcggameDecksRoute
  '/tcggame/duels': typeof TcggameDuelsRoute
  '/tcggame/profile_{$name}': typeof TcggameProfile_Char123nameChar125Route
  '/tcggame/ranking': typeof TcggameRankingRoute
  '/tcggame/trade': typeof TcggameTradeRoute
  '/admin/': typeof AdminIndexRoute
  '/admindev/': typeof AdmindevIndexRoute
  '/tcggame/': typeof TcggameIndexRoute
  '/personagens/$id': typeof AuthenticatedPersonagensIdRoute
  '/admin/crews/$id': typeof AdminCrewsIdRoute
  '/admin/npcs/$id': typeof AdminNpcsIdRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/woptcg/bannerduelo': typeof AdminWoptcgBannerdueloRoute
  '/admin/woptcg/cartas': typeof AdminWoptcgCartasRoute
  '/admin/woptcg/jogadores': typeof AdminWoptcgJogadoresRoute
  '/admindev/crews/$id': typeof AdmindevCrewsIdRoute
  '/admindev/npcs/$id': typeof AdmindevNpcsIdRoute
  '/admindev/players/$id': typeof AdmindevPlayersIdRoute
  '/admindev/woptcg/bannerduelo': typeof AdmindevWoptcgBannerdueloRoute
  '/admindev/woptcg/cartas': typeof AdmindevWoptcgCartasRoute
  '/admindev/woptcg/jogadores': typeof AdmindevWoptcgJogadoresRoute
  '/personagens/': typeof AuthenticatedPersonagensIndexRoute
  '/admin/crews/': typeof AdminCrewsIndexRoute
  '/admin/npcs/': typeof AdminNpcsIndexRoute
  '/admin/woptcg/': typeof AdminWoptcgIndexRoute
  '/admindev/crews/': typeof AdmindevCrewsIndexRoute
  '/admindev/npcs/': typeof AdmindevNpcsIndexRoute
  '/admindev/woptcg/': typeof AdmindevWoptcgIndexRoute
  '/admin/woptcg/jogador/$userId': typeof AdminWoptcgJogadorUserIdRoute
  '/admindev/woptcg/jogador/$userId': typeof AdmindevWoptcgJogadorUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/navio': typeof AuthenticatedNavioRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/tripulacao': typeof AuthenticatedTripulacaoRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admindev/items': typeof AdmindevItemsRoute
  '/admindev/requests': typeof AdmindevRequestsRoute
  '/tcggame/achievements': typeof TcggameAchievementsRoute
  '/tcggame/cards': typeof TcggameCardsRoute
  '/tcggame/craft': typeof TcggameCraftRoute
  '/tcggame/daily': typeof TcggameDailyRoute
  '/tcggame/decks': typeof TcggameDecksRoute
  '/tcggame/duels': typeof TcggameDuelsRoute
  '/tcggame/profile_{$name}': typeof TcggameProfile_Char123nameChar125Route
  '/tcggame/ranking': typeof TcggameRankingRoute
  '/tcggame/trade': typeof TcggameTradeRoute
  '/admin': typeof AdminIndexRoute
  '/admindev': typeof AdmindevIndexRoute
  '/tcggame': typeof TcggameIndexRoute
  '/personagens/$id': typeof AuthenticatedPersonagensIdRoute
  '/admin/crews/$id': typeof AdminCrewsIdRoute
  '/admin/npcs/$id': typeof AdminNpcsIdRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/woptcg/bannerduelo': typeof AdminWoptcgBannerdueloRoute
  '/admin/woptcg/cartas': typeof AdminWoptcgCartasRoute
  '/admin/woptcg/jogadores': typeof AdminWoptcgJogadoresRoute
  '/admindev/crews/$id': typeof AdmindevCrewsIdRoute
  '/admindev/npcs/$id': typeof AdmindevNpcsIdRoute
  '/admindev/players/$id': typeof AdmindevPlayersIdRoute
  '/admindev/woptcg/bannerduelo': typeof AdmindevWoptcgBannerdueloRoute
  '/admindev/woptcg/cartas': typeof AdmindevWoptcgCartasRoute
  '/admindev/woptcg/jogadores': typeof AdmindevWoptcgJogadoresRoute
  '/personagens': typeof AuthenticatedPersonagensIndexRoute
  '/admin/crews': typeof AdminCrewsIndexRoute
  '/admin/npcs': typeof AdminNpcsIndexRoute
  '/admin/woptcg': typeof AdminWoptcgIndexRoute
  '/admindev/crews': typeof AdmindevCrewsIndexRoute
  '/admindev/npcs': typeof AdmindevNpcsIndexRoute
  '/admindev/woptcg': typeof AdmindevWoptcgIndexRoute
  '/admin/woptcg/jogador/$userId': typeof AdminWoptcgJogadorUserIdRoute
  '/admindev/woptcg/jogador/$userId': typeof AdmindevWoptcgJogadorUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admindev': typeof AdmindevRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/tcggame': typeof TcggameRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/navio': typeof AuthenticatedNavioRoute
  '/_authenticated/pets': typeof AuthenticatedPetsRoute
  '/_authenticated/tripulacao': typeof AuthenticatedTripulacaoRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/woptcg': typeof AdminWoptcgRouteWithChildren
  '/admindev/items': typeof AdmindevItemsRoute
  '/admindev/requests': typeof AdmindevRequestsRoute
  '/admindev/woptcg': typeof AdmindevWoptcgRouteWithChildren
  '/tcggame/achievements': typeof TcggameAchievementsRoute
  '/tcggame/cards': typeof TcggameCardsRoute
  '/tcggame/craft': typeof TcggameCraftRoute
  '/tcggame/daily': typeof TcggameDailyRoute
  '/tcggame/decks': typeof TcggameDecksRoute
  '/tcggame/duels': typeof TcggameDuelsRoute
  '/tcggame/profile_{$name}': typeof TcggameProfile_Char123nameChar125Route
  '/tcggame/ranking': typeof TcggameRankingRoute
  '/tcggame/trade': typeof TcggameTradeRoute
  '/admin/': typeof AdminIndexRoute
  '/admindev/': typeof AdmindevIndexRoute
  '/tcggame/': typeof TcggameIndexRoute
  '/_authenticated/personagens/$id': typeof AuthenticatedPersonagensIdRoute
  '/admin/crews/$id': typeof AdminCrewsIdRoute
  '/admin/npcs/$id': typeof AdminNpcsIdRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
  '/admin/woptcg/bannerduelo': typeof AdminWoptcgBannerdueloRoute
  '/admin/woptcg/cartas': typeof AdminWoptcgCartasRoute
  '/admin/woptcg/jogadores': typeof AdminWoptcgJogadoresRoute
  '/admindev/crews/$id': typeof AdmindevCrewsIdRoute
  '/admindev/npcs/$id': typeof AdmindevNpcsIdRoute
  '/admindev/players/$id': typeof AdmindevPlayersIdRoute
  '/admindev/woptcg/bannerduelo': typeof AdmindevWoptcgBannerdueloRoute
  '/admindev/woptcg/cartas': typeof AdmindevWoptcgCartasRoute
  '/admindev/woptcg/jogadores': typeof AdmindevWoptcgJogadoresRoute
  '/_authenticated/personagens/': typeof AuthenticatedPersonagensIndexRoute
  '/admin/crews/': typeof AdminCrewsIndexRoute
  '/admin/npcs/': typeof AdminNpcsIndexRoute
  '/admin/woptcg/': typeof AdminWoptcgIndexRoute
  '/admindev/crews/': typeof AdmindevCrewsIndexRoute
  '/admindev/npcs/': typeof AdmindevNpcsIndexRoute
  '/admindev/woptcg/': typeof AdmindevWoptcgIndexRoute
  '/admin/woptcg/jogador/$userId': typeof AdminWoptcgJogadorUserIdRoute
  '/admindev/woptcg/jogador/$userId': typeof AdmindevWoptcgJogadorUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admindev'
    | '/cadastro'
    | '/entrar'
    | '/tcggame'
    | '/dashboard'
    | '/estoque'
    | '/navio'
    | '/pets'
    | '/tripulacao'
    | '/admin/items'
    | '/admin/requests'
    | '/admin/woptcg'
    | '/admindev/items'
    | '/admindev/requests'
    | '/admindev/woptcg'
    | '/tcggame/achievements'
    | '/tcggame/cards'
    | '/tcggame/craft'
    | '/tcggame/daily'
    | '/tcggame/decks'
    | '/tcggame/duels'
    | '/tcggame/profile_{$name}'
    | '/tcggame/ranking'
    | '/tcggame/trade'
    | '/admin/'
    | '/admindev/'
    | '/tcggame/'
    | '/personagens/$id'
    | '/admin/crews/$id'
    | '/admin/npcs/$id'
    | '/admin/players/$id'
    | '/admin/woptcg/bannerduelo'
    | '/admin/woptcg/cartas'
    | '/admin/woptcg/jogadores'
    | '/admindev/crews/$id'
    | '/admindev/npcs/$id'
    | '/admindev/players/$id'
    | '/admindev/woptcg/bannerduelo'
    | '/admindev/woptcg/cartas'
    | '/admindev/woptcg/jogadores'
    | '/personagens/'
    | '/admin/crews/'
    | '/admin/npcs/'
    | '/admin/woptcg/'
    | '/admindev/crews/'
    | '/admindev/npcs/'
    | '/admindev/woptcg/'
    | '/admin/woptcg/jogador/$userId'
    | '/admindev/woptcg/jogador/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/entrar'
    | '/dashboard'
    | '/estoque'
    | '/navio'
    | '/pets'
    | '/tripulacao'
    | '/admin/items'
    | '/admin/requests'
    | '/admindev/items'
    | '/admindev/requests'
    | '/tcggame/achievements'
    | '/tcggame/cards'
    | '/tcggame/craft'
    | '/tcggame/daily'
    | '/tcggame/decks'
    | '/tcggame/duels'
    | '/tcggame/profile_{$name}'
    | '/tcggame/ranking'
    | '/tcggame/trade'
    | '/admin'
    | '/admindev'
    | '/tcggame'
    | '/personagens/$id'
    | '/admin/crews/$id'
    | '/admin/npcs/$id'
    | '/admin/players/$id'
    | '/admin/woptcg/bannerduelo'
    | '/admin/woptcg/cartas'
    | '/admin/woptcg/jogadores'
    | '/admindev/crews/$id'
    | '/admindev/npcs/$id'
    | '/admindev/players/$id'
    | '/admindev/woptcg/bannerduelo'
    | '/admindev/woptcg/cartas'
    | '/admindev/woptcg/jogadores'
    | '/personagens'
    | '/admin/crews'
    | '/admin/npcs'
    | '/admin/woptcg'
    | '/admindev/crews'
    | '/admindev/npcs'
    | '/admindev/woptcg'
    | '/admin/woptcg/jogador/$userId'
    | '/admindev/woptcg/jogador/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admindev'
    | '/cadastro'
    | '/entrar'
    | '/tcggame'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/navio'
    | '/_authenticated/pets'
    | '/_authenticated/tripulacao'
    | '/admin/items'
    | '/admin/requests'
    | '/admin/woptcg'
    | '/admindev/items'
    | '/admindev/requests'
    | '/admindev/woptcg'
    | '/tcggame/achievements'
    | '/tcggame/cards'
    | '/tcggame/craft'
    | '/tcggame/daily'
    | '/tcggame/decks'
    | '/tcggame/duels'
    | '/tcggame/profile_{$name}'
    | '/tcggame/ranking'
    | '/tcggame/trade'
    | '/admin/'
    | '/admindev/'
    | '/tcggame/'
    | '/_authenticated/personagens/$id'
    | '/admin/crews/$id'
    | '/admin/npcs/$id'
    | '/admin/players/$id'
    | '/admin/woptcg/bannerduelo'
    | '/admin/woptcg/cartas'
    | '/admin/woptcg/jogadores'
    | '/admindev/crews/$id'
    | '/admindev/npcs/$id'
    | '/admindev/players/$id'
    | '/admindev/woptcg/bannerduelo'
    | '/admindev/woptcg/cartas'
    | '/admindev/woptcg/jogadores'
    | '/_authenticated/personagens/'
    | '/admin/crews/'
    | '/admin/npcs/'
    | '/admin/woptcg/'
    | '/admindev/crews/'
    | '/admindev/npcs/'
    | '/admindev/woptcg/'
    | '/admin/woptcg/jogador/$userId'
    | '/admindev/woptcg/jogador/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdmindevRoute: typeof AdmindevRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  TcggameRoute: typeof TcggameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tcggame': {
      id: '/tcggame'
      path: '/tcggame'
      fullPath: '/tcggame'
      preLoaderRoute: typeof TcggameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindev': {
      id: '/admindev'
      path: '/admindev'
      fullPath: '/admindev'
      preLoaderRoute: typeof AdmindevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tcggame/': {
      id: '/tcggame/'
      path: '/'
      fullPath: '/tcggame/'
      preLoaderRoute: typeof TcggameIndexRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/admindev/': {
      id: '/admindev/'
      path: '/'
      fullPath: '/admindev/'
      preLoaderRoute: typeof AdmindevIndexRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tcggame/trade': {
      id: '/tcggame/trade'
      path: '/trade'
      fullPath: '/tcggame/trade'
      preLoaderRoute: typeof TcggameTradeRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/ranking': {
      id: '/tcggame/ranking'
      path: '/ranking'
      fullPath: '/tcggame/ranking'
      preLoaderRoute: typeof TcggameRankingRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/profile_{$name}': {
      id: '/tcggame/profile_{$name}'
      path: '/profile_{$name}'
      fullPath: '/tcggame/profile_{$name}'
      preLoaderRoute: typeof TcggameProfile_Char123nameChar125RouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/duels': {
      id: '/tcggame/duels'
      path: '/duels'
      fullPath: '/tcggame/duels'
      preLoaderRoute: typeof TcggameDuelsRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/decks': {
      id: '/tcggame/decks'
      path: '/decks'
      fullPath: '/tcggame/decks'
      preLoaderRoute: typeof TcggameDecksRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/daily': {
      id: '/tcggame/daily'
      path: '/daily'
      fullPath: '/tcggame/daily'
      preLoaderRoute: typeof TcggameDailyRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/craft': {
      id: '/tcggame/craft'
      path: '/craft'
      fullPath: '/tcggame/craft'
      preLoaderRoute: typeof TcggameCraftRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/cards': {
      id: '/tcggame/cards'
      path: '/cards'
      fullPath: '/tcggame/cards'
      preLoaderRoute: typeof TcggameCardsRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/tcggame/achievements': {
      id: '/tcggame/achievements'
      path: '/achievements'
      fullPath: '/tcggame/achievements'
      preLoaderRoute: typeof TcggameAchievementsRouteImport
      parentRoute: typeof TcggameRoute
    }
    '/admindev/woptcg': {
      id: '/admindev/woptcg'
      path: '/woptcg'
      fullPath: '/admindev/woptcg'
      preLoaderRoute: typeof AdmindevWoptcgRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admindev/requests': {
      id: '/admindev/requests'
      path: '/requests'
      fullPath: '/admindev/requests'
      preLoaderRoute: typeof AdmindevRequestsRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admindev/items': {
      id: '/admindev/items'
      path: '/items'
      fullPath: '/admindev/items'
      preLoaderRoute: typeof AdmindevItemsRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admin/woptcg': {
      id: '/admin/woptcg'
      path: '/woptcg'
      fullPath: '/admin/woptcg'
      preLoaderRoute: typeof AdminWoptcgRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/tripulacao': {
      id: '/_authenticated/tripulacao'
      path: '/tripulacao'
      fullPath: '/tripulacao'
      preLoaderRoute: typeof AuthenticatedTripulacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pets': {
      id: '/_authenticated/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AuthenticatedPetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/navio': {
      id: '/_authenticated/navio'
      path: '/navio'
      fullPath: '/navio'
      preLoaderRoute: typeof AuthenticatedNavioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admindev/woptcg/': {
      id: '/admindev/woptcg/'
      path: '/'
      fullPath: '/admindev/woptcg/'
      preLoaderRoute: typeof AdmindevWoptcgIndexRouteImport
      parentRoute: typeof AdmindevWoptcgRoute
    }
    '/admindev/npcs/': {
      id: '/admindev/npcs/'
      path: '/npcs'
      fullPath: '/admindev/npcs/'
      preLoaderRoute: typeof AdmindevNpcsIndexRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admindev/crews/': {
      id: '/admindev/crews/'
      path: '/crews'
      fullPath: '/admindev/crews/'
      preLoaderRoute: typeof AdmindevCrewsIndexRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admin/woptcg/': {
      id: '/admin/woptcg/'
      path: '/'
      fullPath: '/admin/woptcg/'
      preLoaderRoute: typeof AdminWoptcgIndexRouteImport
      parentRoute: typeof AdminWoptcgRoute
    }
    '/admin/npcs/': {
      id: '/admin/npcs/'
      path: '/npcs'
      fullPath: '/admin/npcs/'
      preLoaderRoute: typeof AdminNpcsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crews/': {
      id: '/admin/crews/'
      path: '/crews'
      fullPath: '/admin/crews/'
      preLoaderRoute: typeof AdminCrewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/personagens/': {
      id: '/_authenticated/personagens/'
      path: '/personagens'
      fullPath: '/personagens/'
      preLoaderRoute: typeof AuthenticatedPersonagensIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admindev/woptcg/jogadores': {
      id: '/admindev/woptcg/jogadores'
      path: '/jogadores'
      fullPath: '/admindev/woptcg/jogadores'
      preLoaderRoute: typeof AdmindevWoptcgJogadoresRouteImport
      parentRoute: typeof AdmindevWoptcgRoute
    }
    '/admindev/woptcg/cartas': {
      id: '/admindev/woptcg/cartas'
      path: '/cartas'
      fullPath: '/admindev/woptcg/cartas'
      preLoaderRoute: typeof AdmindevWoptcgCartasRouteImport
      parentRoute: typeof AdmindevWoptcgRoute
    }
    '/admindev/woptcg/bannerduelo': {
      id: '/admindev/woptcg/bannerduelo'
      path: '/bannerduelo'
      fullPath: '/admindev/woptcg/bannerduelo'
      preLoaderRoute: typeof AdmindevWoptcgBannerdueloRouteImport
      parentRoute: typeof AdmindevWoptcgRoute
    }
    '/admindev/players/$id': {
      id: '/admindev/players/$id'
      path: '/players/$id'
      fullPath: '/admindev/players/$id'
      preLoaderRoute: typeof AdmindevPlayersIdRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admindev/npcs/$id': {
      id: '/admindev/npcs/$id'
      path: '/npcs/$id'
      fullPath: '/admindev/npcs/$id'
      preLoaderRoute: typeof AdmindevNpcsIdRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admindev/crews/$id': {
      id: '/admindev/crews/$id'
      path: '/crews/$id'
      fullPath: '/admindev/crews/$id'
      preLoaderRoute: typeof AdmindevCrewsIdRouteImport
      parentRoute: typeof AdmindevRoute
    }
    '/admin/woptcg/jogadores': {
      id: '/admin/woptcg/jogadores'
      path: '/jogadores'
      fullPath: '/admin/woptcg/jogadores'
      preLoaderRoute: typeof AdminWoptcgJogadoresRouteImport
      parentRoute: typeof AdminWoptcgRoute
    }
    '/admin/woptcg/cartas': {
      id: '/admin/woptcg/cartas'
      path: '/cartas'
      fullPath: '/admin/woptcg/cartas'
      preLoaderRoute: typeof AdminWoptcgCartasRouteImport
      parentRoute: typeof AdminWoptcgRoute
    }
    '/admin/woptcg/bannerduelo': {
      id: '/admin/woptcg/bannerduelo'
      path: '/bannerduelo'
      fullPath: '/admin/woptcg/bannerduelo'
      preLoaderRoute: typeof AdminWoptcgBannerdueloRouteImport
      parentRoute: typeof AdminWoptcgRoute
    }
    '/admin/players/$id': {
      id: '/admin/players/$id'
      path: '/players/$id'
      fullPath: '/admin/players/$id'
      preLoaderRoute: typeof AdminPlayersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/npcs/$id': {
      id: '/admin/npcs/$id'
      path: '/npcs/$id'
      fullPath: '/admin/npcs/$id'
      preLoaderRoute: typeof AdminNpcsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crews/$id': {
      id: '/admin/crews/$id'
      path: '/crews/$id'
      fullPath: '/admin/crews/$id'
      preLoaderRoute: typeof AdminCrewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/personagens/$id': {
      id: '/_authenticated/personagens/$id'
      path: '/personagens/$id'
      fullPath: '/personagens/$id'
      preLoaderRoute: typeof AuthenticatedPersonagensIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admindev/woptcg/jogador/$userId': {
      id: '/admindev/woptcg/jogador/$userId'
      path: '/jogador/$userId'
      fullPath: '/admindev/woptcg/jogador/$userId'
      preLoaderRoute: typeof AdmindevWoptcgJogadorUserIdRouteImport
      parentRoute: typeof AdmindevWoptcgRoute
    }
    '/admin/woptcg/jogador/$userId': {
      id: '/admin/woptcg/jogador/$userId'
      path: '/jogador/$userId'
      fullPath: '/admin/woptcg/jogador/$userId'
      preLoaderRoute: typeof AdminWoptcgJogadorUserIdRouteImport
      parentRoute: typeof AdminWoptcgRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedNavioRoute: typeof AuthenticatedNavioRoute
  AuthenticatedPetsRoute: typeof AuthenticatedPetsRoute
  AuthenticatedTripulacaoRoute: typeof AuthenticatedTripulacaoRoute
  AuthenticatedPersonagensIdRoute: typeof AuthenticatedPersonagensIdRoute
  AuthenticatedPersonagensIndexRoute: typeof AuthenticatedPersonagensIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedNavioRoute: AuthenticatedNavioRoute,
  AuthenticatedPetsRoute: AuthenticatedPetsRoute,
  AuthenticatedTripulacaoRoute: AuthenticatedTripulacaoRoute,
  AuthenticatedPersonagensIdRoute: AuthenticatedPersonagensIdRoute,
  AuthenticatedPersonagensIndexRoute: AuthenticatedPersonagensIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminWoptcgRouteChildren {
  AdminWoptcgBannerdueloRoute: typeof AdminWoptcgBannerdueloRoute
  AdminWoptcgCartasRoute: typeof AdminWoptcgCartasRoute
  AdminWoptcgJogadoresRoute: typeof AdminWoptcgJogadoresRoute
  AdminWoptcgIndexRoute: typeof AdminWoptcgIndexRoute
  AdminWoptcgJogadorUserIdRoute: typeof AdminWoptcgJogadorUserIdRoute
}

const AdminWoptcgRouteChildren: AdminWoptcgRouteChildren = {
  AdminWoptcgBannerdueloRoute: AdminWoptcgBannerdueloRoute,
  AdminWoptcgCartasRoute: AdminWoptcgCartasRoute,
  AdminWoptcgJogadoresRoute: AdminWoptcgJogadoresRoute,
  AdminWoptcgIndexRoute: AdminWoptcgIndexRoute,
  AdminWoptcgJogadorUserIdRoute: AdminWoptcgJogadorUserIdRoute,
}

const AdminWoptcgRouteWithChildren = AdminWoptcgRoute._addFileChildren(
  AdminWoptcgRouteChildren,
)

interface AdminRouteChildren {
  AdminItemsRoute: typeof AdminItemsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminWoptcgRoute: typeof AdminWoptcgRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCrewsIdRoute: typeof AdminCrewsIdRoute
  AdminNpcsIdRoute: typeof AdminNpcsIdRoute
  AdminPlayersIdRoute: typeof AdminPlayersIdRoute
  AdminCrewsIndexRoute: typeof AdminCrewsIndexRoute
  AdminNpcsIndexRoute: typeof AdminNpcsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminItemsRoute: AdminItemsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminWoptcgRoute: AdminWoptcgRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCrewsIdRoute: AdminCrewsIdRoute,
  AdminNpcsIdRoute: AdminNpcsIdRoute,
  AdminPlayersIdRoute: AdminPlayersIdRoute,
  AdminCrewsIndexRoute: AdminCrewsIndexRoute,
  AdminNpcsIndexRoute: AdminNpcsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdmindevWoptcgRouteChildren {
  AdmindevWoptcgBannerdueloRoute: typeof AdmindevWoptcgBannerdueloRoute
  AdmindevWoptcgCartasRoute: typeof AdmindevWoptcgCartasRoute
  AdmindevWoptcgJogadoresRoute: typeof AdmindevWoptcgJogadoresRoute
  AdmindevWoptcgIndexRoute: typeof AdmindevWoptcgIndexRoute
  AdmindevWoptcgJogadorUserIdRoute: typeof AdmindevWoptcgJogadorUserIdRoute
}

const AdmindevWoptcgRouteChildren: AdmindevWoptcgRouteChildren = {
  AdmindevWoptcgBannerdueloRoute: AdmindevWoptcgBannerdueloRoute,
  AdmindevWoptcgCartasRoute: AdmindevWoptcgCartasRoute,
  AdmindevWoptcgJogadoresRoute: AdmindevWoptcgJogadoresRoute,
  AdmindevWoptcgIndexRoute: AdmindevWoptcgIndexRoute,
  AdmindevWoptcgJogadorUserIdRoute: AdmindevWoptcgJogadorUserIdRoute,
}

const AdmindevWoptcgRouteWithChildren = AdmindevWoptcgRoute._addFileChildren(
  AdmindevWoptcgRouteChildren,
)

interface AdmindevRouteChildren {
  AdmindevItemsRoute: typeof AdmindevItemsRoute
  AdmindevRequestsRoute: typeof AdmindevRequestsRoute
  AdmindevWoptcgRoute: typeof AdmindevWoptcgRouteWithChildren
  AdmindevIndexRoute: typeof AdmindevIndexRoute
  AdmindevCrewsIdRoute: typeof AdmindevCrewsIdRoute
  AdmindevNpcsIdRoute: typeof AdmindevNpcsIdRoute
  AdmindevPlayersIdRoute: typeof AdmindevPlayersIdRoute
  AdmindevCrewsIndexRoute: typeof AdmindevCrewsIndexRoute
  AdmindevNpcsIndexRoute: typeof AdmindevNpcsIndexRoute
}

const AdmindevRouteChildren: AdmindevRouteChildren = {
  AdmindevItemsRoute: AdmindevItemsRoute,
  AdmindevRequestsRoute: AdmindevRequestsRoute,
  AdmindevWoptcgRoute: AdmindevWoptcgRouteWithChildren,
  AdmindevIndexRoute: AdmindevIndexRoute,
  AdmindevCrewsIdRoute: AdmindevCrewsIdRoute,
  AdmindevNpcsIdRoute: AdmindevNpcsIdRoute,
  AdmindevPlayersIdRoute: AdmindevPlayersIdRoute,
  AdmindevCrewsIndexRoute: AdmindevCrewsIndexRoute,
  AdmindevNpcsIndexRoute: AdmindevNpcsIndexRoute,
}

const AdmindevRouteWithChildren = AdmindevRoute._addFileChildren(
  AdmindevRouteChildren,
)

interface TcggameRouteChildren {
  TcggameAchievementsRoute: typeof TcggameAchievementsRoute
  TcggameCardsRoute: typeof TcggameCardsRoute
  TcggameCraftRoute: typeof TcggameCraftRoute
  TcggameDailyRoute: typeof TcggameDailyRoute
  TcggameDecksRoute: typeof TcggameDecksRoute
  TcggameDuelsRoute: typeof TcggameDuelsRoute
  TcggameProfile_Char123nameChar125Route: typeof TcggameProfile_Char123nameChar125Route
  TcggameRankingRoute: typeof TcggameRankingRoute
  TcggameTradeRoute: typeof TcggameTradeRoute
  TcggameIndexRoute: typeof TcggameIndexRoute
}

const TcggameRouteChildren: TcggameRouteChildren = {
  TcggameAchievementsRoute: TcggameAchievementsRoute,
  TcggameCardsRoute: TcggameCardsRoute,
  TcggameCraftRoute: TcggameCraftRoute,
  TcggameDailyRoute: TcggameDailyRoute,
  TcggameDecksRoute: TcggameDecksRoute,
  TcggameDuelsRoute: TcggameDuelsRoute,
  TcggameProfile_Char123nameChar125Route:
    TcggameProfile_Char123nameChar125Route,
  TcggameRankingRoute: TcggameRankingRoute,
  TcggameTradeRoute: TcggameTradeRoute,
  TcggameIndexRoute: TcggameIndexRoute,
}

const TcggameRouteWithChildren =
  TcggameRoute._addFileChildren(TcggameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdmindevRoute: AdmindevRouteWithChildren,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  TcggameRoute: TcggameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
