import type { ProfessionData } from "./types";

export const ARTISTA: ProfessionData = {
  id: "artista",
  name: "Artista",
  description:
    "Os artistas são indivíduos talentosos que são capazes de sobreviver e fazer grande quantidade de dinheiro através de manifestações artísticas especializadas. Um artista, no momento em que inicia sua carreira, precisa escolher uma área de foco, como por exemplo a dança, a escultura, a música, a pintura... É comum encontrar artistas pelas muitas cidades do mundo, conquistando o coração de donzelas e o bolso de burgueses, pois suas manifestações artísticas são cativantes e carismáticas.\n\nInicialmente, os personagens que seguem este caminho iniciam na profissão Artista, e eventualmente podem se especializar e se tornar Criadores ou Performáticos.\n\nCaso se torne um Criador, evolui para o domínio Midas ou Mímico.\n\nCaso se torne um Performático, evolui para o domínio Showman ou Charlatão.",
  initialAbilities: [
    { tier: "INICIAL", title: "Nasce uma Estrela", body: "Os artistas precisam escolher uma área de conhecimento entre: Atuação, Dança, Escultura, Música, Pintura e Poesia. Enquanto exerce qualquer ação que desencadeia um Teste de Artista na área escolhida, o personagem recebe um acréscimo de modificadores de 06 por Tier da profissão (Inicial = 0)." },
    { tier: "TIER_I", title: "Início de Carreira", body: "O artista se torna capaz de desenvolver uma manifestação artística em público para atrair dinheiro aos seus fundos econômicos. Através do uso dessa habilidade, o artista deve realizar sua performance artística em um local movimentado, e a depender de seu resultado em um Teste de Artista, ele poderá atrair indivíduos que o recompensem por seu talento. A dificuldade mínima para essa habilidade é 15, recebendo 1.500.000 Berries de doações. Caso alcance um resultado superior a 20 recebe 3.000.000 de Berries e caso atinja um resultado perfeito (26) receberá 6.000.000 Berries. A eficácia dessa habilidade é dependente da localidade utilizada, e o artista não pode receber mais que uma recompensa da mesma ilha em um período de uma semana." },
    { tier: "TIER_II", title: "Performático Promissor", body: "O artista se torna capaz de utilizar da arte do improviso para entreter um grupo de até 3 indivíduos com uma performance de sua área de atuação. Ao realizar essa ação, o artista poderá realizar uma rolagem de Teste de Artista, e ao alcançar no mínimo 22 de resultado, consegue entreter os indivíduos próximos, regenerando 100 de SP dos envolvidos, regenerando +10 de SP para cada número superior a 22 alcançado na rolagem de Artista (Máx. 200 de SP). Em batalhas, essa habilidade possui uma recarga de três turnos e consome o turno do Artista." },
    { tier: "TIER_III", title: "Criador Promissor", body: "A cada 3 sessões, o artista torna-se capaz de fazer uma criação dentro de sua área de conhecimento. Quando exibir essa obra de arte pela primeira vez, todos os aliados do artista que a vislumbrar serão inspirados por seu avanço na carreira, recebendo uma bonificação de +3 em todas as rolagens durante toda a sessão." },
  ],
  specializations: [
    {
      id: "criador",
      name: "Criador",
      description:
        "Os Criadores são artistas que se especializam na criação, pecando na performance para focar em obras de artes que arrebatam os sentimentos daqueles que as vislumbram. Os Criadores passam uma grande quantia de tempo trabalhando na confecção de sua Magnum Opus, a sua obra-prima artística, que ao ser concluída, pode ser vendida a indivíduos interessados por até $50.000.000.",
      abilities: [
        { tier: "TIER_IV", title: "Magnum Opus", body: "Ao escolher a especialização Criador, o Artista começa o desenvolvimento de sua Magnum Opus. Trata-se da maior obra-prima de sua carreira como artista, a qual entrega boa parte de seu tempo. Ao alcançar esse Tier, o Criador recebe um contador em sua ficha, indicando a porcentagem de conclusão de sua obra-prima. Ao atingir os 100%, a Magnum Opus está pronta. As habilidades futuras do artista podem aumentar ou reduzir o seu contador de Magnum Opus. Durante longas passagens de tempo, deve-se rolar 1d6 para determinar a porcentagem de completude de sua Magnum Opus. Essa rolagem só pode ocorrer, no máximo, uma vez por sessão." },
        { tier: "TIER_V", title: "Período de Foco", body: "Ao alcançar esse Tier, o artista passa a ser capaz de utilizar grandes períodos de concentração para se focar na conclusão de sua obra-prima. Ao esforçar-se para concluir sua obra-prima com essa habilidade, o personagem deverá realizar um Teste de Artista e a depender do resultado influenciará de determinada maneira sua Magnum Opus. Ao atingir um resultado inferior a 40, perde-se 10% de sua barra de conclusão. Ao atingir resultado superior a 40, recebe +5% de conclusão; Ao atingir resultado superior a 45, recebe +10% de conclusão; Ao atingir resultado superior a 50, recebe +15% de conclusão. Essa habilidade só pode ser utilizada uma vez a cada três sessões." },
        { tier: "TIER_VI", title: "Vislumbre da Perfeição", body: "Com esse Tier de desenvolvimento de suas habilidades, o Artista passa a receber a capacidade de utilizar a habilidade “Período de Foco” uma vez a cada duas sessões e realiza o Teste de Artista com vantagem, desde que sua primeira Magnum Opus ainda não tenha sido criada. Além disso, nesse nível o Criador adquire a capacidade de demonstrar um vislumbre de sua futura obra-prima (ainda incompleta) para outros indivíduos, e ao fazer isso, concede a eles uma bonificação inspiradora de +6 em sua próxima rolagem. Essa habilidade só funciona uma vez por pessoa (por Magnum Opus), e consome o turno do artista." },
        { tier: "TIER_VII", title: "Contemplar da Obra Divina", body: "Ao alcançar o ápice de suas habilidades como um criador, o artista recebe a capacidade de expor sua Magnum Opus em seu estado mais completo e glorioso. Ao consumir seu turno expondo sua criação, todos os indivíduos aliados que estejam a vislumbrando pela primeira vez recebem um bônus de vantagem em todos os testes de Força de Vontade, além de conceder a todos os influenciados um desconto de 15% no gasto de energia. As bonificações concedidas por esse movimento só duram durante a cena atual, e o artista necessita consumir seu turno demonstrando sua criação. Os indivíduos são impossibilitados de serem inspirados mais do que uma vez por Magnum Opus." },
      ],
      domains: [
        {
          id: "midas",
          name: "Midas",
          description:
            "Os Midas são artistas que se especializam em suas criações e adentram o domínio do Midas, famigerados por darem ênfase na mescla dos sentimentos com suas criações, alcançando um novo patamar criativo que elucida as obras do artista como dignas das etiquetas de valores mais altas. As Magnum Opus confeccionadas pelos Midas podem alcançar valores de até $250.000.000.",
          abilities: [
            { tier: "TIER_VIII", title: "Tempo é Dinheiro", body: "Ao atingir esse Tier de profissão, o personagem pode consolidar-se no domínio do Midas. Fazendo isso, ele se torna uma figura conhecida mundialmente pelas suas famigeradas criações que carregam emoções e histórias, tornando-as famosas nos mares. Ao atingir esse nível de habilidade e adentrar o domínio de Midas, o personagem passa a ser capaz de receber “Orgulho do Criador”, uma bonificação de +3 em todos seus modificadores durante duas sessões, recebido após vender uma Magnum Opus. Por conta de seu domínio sobre o uso dos sentimentos para fazer dinheiro, o personagem deixa de receber 06 de modificador em Testes de Artista por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Período Azul", body: "A partir desse nível de perícia profissional, o Midas começa a conseguir espremer seus sentimentos para nutrir suas criações. Através dessa habilidade, o artista consegue adentrar um período melancólico no momento em que sente a perda de algum indivíduo que considerava querido. Essa habilidade mantém-se ativa durante os próximos três “Períodos de Foco”, dobrando todas as recompensas alcançadas pelo uso da habilidade. Quando uma Magnum Opus é criada dentro do Período Azul, ela torna-se uma recordação do ente perdido, e o Midas torna-se impossibilitado de vendê-la. No entanto, uma vez a cada dez sessões, o Midas pode utilizar sua Magnum Opus para relembrar seus aliados do indivíduo que se foi, concedendo a todos uma bonificação de +6 em todas as rolagens até o fim da sessão." },
            { tier: "TIER_X", title: "Oferta e Demanda", body: "A partir desse nível profissional, o Midas começa a ser capaz de ouvir as histórias de outros indivíduos sobre entes queridos e/ou perdidos, e são capazes de canalizar essas emoções para construir uma Magnum Opus específica para as histórias ouvidas. Caso utilize essa habilidade para ouvir as histórias de outro indivíduo e resolva construir uma nova Magnum Opus, recebe instantaneamente 30% de conclusão para a Magnum Opus. Se essa peça for vendida para o indivíduo que contou as histórias a respeito do sujeito-inspiração, o preço da Magnum Opus pode aumentar até o dobro de seu valor basal estabelecido pelo domínio do Midas." },
            { tier: "TIER_XX", title: "Magnum Opus Maravilhosa", body: "No auge de sua profissão e carreira, o Midas consegue criar uma Magnum Opus suprema, que está acima de todas as outras que já conseguiu criar. Essa Magnum Opus incorpora em si todas as lutas, perdas e vivências da aventura do artista, trazendo consigo um imensurável peso sentimental. Essa criação trata-se de uma maravilha, uma relíquia do mundo que faz o Midas finalmente alcançar a fama mundial, pela criação de uma obra prima que transcende os valores físicos que o dinheiro consegue alcançar. Essa Magnum Opus única e não replicável pode ser vendida por qualquer valor, sendo uma peça singular em todo o mundo. Depois de finalizar a criação de sua Magnum Opus Maravilhosa, o artista recebe permanentemente vantagem em qualquer teste de Força de Vontade, além de tornar-se uma figura reconhecida mundialmente por sua criação." },
          ],
        },
        {
          id: "mimico",
          name: "Mímico",
          description:
            "Os Mímicos são artistas que se especializaram em observar as obras de outros artistas ou os movimentos de outros indivíduos, inspirando-se naquilo que já foi criado por outrem para a confecção de suas Magnum Opus. Esse domínio também possibilita ao Mímico imitar completamente os trejeitos de um indivíduo. Por padrão, as Magnum Opus de Mímicos são vendidas por, no máximo, $100.000.000.",
          abilities: [
            { tier: "TIER_VIII", title: "Não é plágio, é inspiração!", body: "Ao atingir esse Tier de profissão, o personagem pode consolidar-se no domínio do Mímico. Fazendo isso, ele se torna um especialista em “inspirações”, observando cautelosamente os trabalhos de outros e inspirando-se neles para a aceleração do seu processo de criação de Magnum Opus. Ao atingir esse Tier, o personagem recebe a mecânica de “Inspiração”. Quando vislumbra pela primeira vez uma Magnum Opus de outro artista, recebe instantaneamente 5 Pontos de Inspiração. Ao vislumbrar o uso de algum movimento de estilo de luta pela primeira vez, o artista é capaz de realizar um Teste de Artista, e ao alcançar resultado igual ou superior a 68, recebe 1 Ponto de Inspiração. Cada Ponto de Inspiração pode ser consumido para aumentar o progresso de construção de uma Magnum Opus em 10%. Por conta de seu domínio, o personagem deixa de receber 06 de modificador em Testes de Artista por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Não tão Original", body: "A partir desse nível, o Mímico torna-se capaz de realizar a venda de sua Magnum Opus por um valor um pouco maior. Sempre que tiver a oportunidade de conversar com um comprador sobre a veracidade de sua autenticidade, o Mímico pode realizar um Teste de Artista com Dificuldade 75. Em sucessos, o Mímico consegue triplicar o valor de sua Magnum Opus para o indivíduo em questão, que irá acreditar na originalidade da obra de arte. Essa habilidade só pode ser utilizada uma vez por Magnum Opus criada pelo Mímico." },
            { tier: "TIER_X", title: "Roubo do Protagonismo", body: "Ao alcançar esse nível de perícia em sua profissão, o artista consegue utilizar suas habilidades sobre o domínio do Mímico para a personificação de outrem. Quando utiliza essa habilidade, o Mímico entra no personagem e consegue imitar completamente todos os trejeitos de um indivíduo em específico. Com isso, é capaz de reproduzir a maneira de andar, falar e pensar de um sujeito que tenha observado com cautela por um grande período de tempo." },
            { tier: "TIER_XX", title: "Beijo Final", body: "Nesse Tier, o Mímico torna-se o plagiador entre os plagiadores. Através dessa habilidade, o Mímico é capaz de observar cautelosamente a execução de qualquer manifestação artística ou movimento de estilo de luta. Caso possua os meios necessários para tal, o Mímico adquire a habilidade de replicar com exatidão tudo aquilo que foi observado, plagiando golpes assinaturas de outros indivíduos e até mesmo conseguindo roubar completamente a ideia de sua Magnum Opus. Caso o Mímico utilize esse movimento para plagiar uma Magnum Opus, ele conseguirá criá-la uma vez sem a necessidade de preenchimento da porcentagem de conclusão." },
          ],
        },
      ],
    },
    {
      id: "performatico",
      name: "Performático",
      description:
        "Os Performáticos são artistas cuja fama está em ascensão. Estes artistas especializados começam a conquistar grandes públicos espalhando sua fama através de fãs fervorosos que estão dispostos a abdicar de suas próprias economias para fazer com que a vida do artista seja ainda mais luxuosa.",
      abilities: [
        { tier: "TIER_IV", title: "Público Alvo", body: "Ao escolher a especialização Performático, o Artista começa a desenvolver uma relação com indivíduos que se auto intitulam seus “fãs”. No momento em que alcança esse Tier de sua profissão, o personagem recebe um contador especial de “Fãs”, com uma quantia igual a 1d100 (Máx. 100). As habilidades futuras do artista podem aumentar ou reduzir o seu contador de Fãs. Ao locomover-se pelas localizações de uma ilha, deve-se rolar 1d100, e em resultados inferiores ao seu Contador de Fãs, o personagem irá encontrar pelo menos um de seus fãs." },
        { tier: "TIER_V", title: "Conquistador de Corações", body: "Ao alcançar esse Tier de profissão, a habilidade do Artista “Performático Promissor” passa a conceder +3 Contadores de Fãs em resultados acima de 40, aumentando para +6 em resultados acima de 45 e para +9 em resultados iguais ou superiores a 50. Qualquer resultado inferior a 40 irá acarretar na perda de 10 Fãs." },
        { tier: "TIER_VI", title: "Mimos & Recebidos", body: "Atingindo esse Tier de profissão, o Performático recebe a capacidade de aumentar ainda mais a sua fama nas ilhas de World of Piece. Quando utiliza o movimento “Performático Promissor”, caso atinja um resultado superior a 55, parte da multidão irá se juntar para criar um Fã Clube do personagem na ilha em questão. Uma vez a cada três sessões, o personagem irá receber uma encomenda de cada Fã Clube que possuir, sendo um presente de Berries de valor igual a 1d10 Milhões." },
        { tier: "TIER_VII", title: "Agenda Cheia", body: "Ao obter essa habilidade, o Performático adquire a possibilidade de agendar um evento em uma ilha, performando um Show de sua área de atuação para os cidadãos. Essa habilidade deve ser usada com pelo menos uma sessão de antecedência, necessitando de um período de pelo menos 1 semana de antecedência in-game para preparação. Após realizar o Show, o usuário irá receber 1d10 Milhões para cada Fã Clube que possuir, devido a presença de seus fãs. Além disso, recebe +10 Contadores de Fãs e cria 1 Fã Clube na ilha onde fez o show. Essa habilidade só pode ser utilizada uma vez a cada 7 sessões." },
      ],
      domains: [
        {
          id: "showman",
          name: "Showman",
          description:
            "Os Showman são artistas que se especializaram em performances e adentraram o domínio dos espetáculos. Através de seus conhecimentos cênicos obtidos durante seu longo percurso como um artista, começam a ser capazes de reutilizar suas habilidades de palco para interferirem de maneira impactante no campo de batalha, atraindo a atenção de seus inimigos para proteger seus aliados ou até mesmo inspirando os seus aliados em um momento de enorme necessidade para finalizar o combate.",
          abilities: [
            { tier: "TIER_VIII", title: "Calçada da Fama", body: "Ao atingir esse Tier de profissão, o personagem pode consolidar-se no domínio do Showman. Fazendo isso, ele se torna um verdadeiro ídolo entre as múltiplas figuras de fama mundial. O personagem recebe a capacidade de Assinar Autógrafos de seus fãs, criando relíquias de seu legado como artista. Por conta de seu domínio sobre a arte, o personagem deixa de receber 06 de modificador em Testes de Artista por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Ato Principal", body: "Utilizando essa habilidade, o Artista começa a trazer todos os conhecimentos adquiridos em seu percurso na área para o campo de batalha. O Showman inicia a sua performance, capturando a atenção de todos os presentes no campo de batalha. Ao utilizar essa habilidade e enquanto mantê-la ativa, o usuário torna-se o foco de todos os inimigos próximos, atraindo a atenção para si. Durante o uso dessa habilidade, os oponentes do artista perderão 50% de seus modificadores ao realizarem ações ofensivas contra alvos que não sejam o próprio artista. Caso o artista receba um golpe, essa habilidade é cancelada. Essa habilidade possui 3 turnos de Tempo de Recarga e consome a Ação do Artista." },
            { tier: "TIER_X", title: "Bis", body: "Ao alcançar esse Tier, o Showman descobre a arte de influenciar outros indivíduos a partir de seus conhecimentos artísticos. Por meio dessa habilidade o artista consegue forçar um alvo próximo a repetir o último movimento que utilizou, ignorando o tempo de recarga, contudo mantém-se os gastos e é necessário que o movimento seja utilizado consumindo o próximo turno de ataque do personagem alvejado. Esse movimento especial não possui custo de energia, contudo possui 10 turnos de recarga." },
            { tier: "TIER_XX", title: "Grand Finale", body: "O Showman utiliza todos os seus aprendizados como um artista para realizar o seu último ato — um Último Movimento acompanhado de todos os membros da tripulação do artista. Ao declarar o uso desse movimento, o artista começa a sua performance artística consumindo inteiramente a sua barra de energia. Através do uso dessa habilidade o artista permite que todos os membros de sua tripulação utilizem uma habilidade gratuitamente, sem o gasto de energia. Esse movimento só pode ser utilizado caso um dos aliados do artista tenha recebido um golpe fatal ou caso pelo menos três aliados do artista estejam perto da morte. Com o fim desse movimento, o artista desmaia." },
          ],
        },
        {
          id: "charlatao",
          name: "Charlatão",
          description:
            "Os Charlatões são artistas que se especializaram em performances oportunistas e abusam de sua influência e talento para adquirir a atenção do seu público para conquistar aquilo que não possui. Começam a ser capazes de reutilizar suas habilidades de palco para interferirem no campo de batalha, atraindo a atenção de seus inimigos para proteger a si mesmo ou roubar seus pertences.",
          abilities: [
            { tier: "TIER_VIII", title: "Legado Assegurado", body: "Ao atingir esse Tier de profissão, o personagem pode consolidar-se no domínio do Charlatão. Fazendo isso, ele se torna um verdadeiro ídolo entre as múltiplas figuras de fama mundial. O personagem recebe a capacidade de Assinar Autógrafos de seus fãs, criando relíquias de seu legado como artista. Por conta de seu domínio sobre a arte, o personagem deixa de receber 06 de modificador em Testes de Artista por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Isso é seu?", body: "Através do uso dessa habilidade, o charlatão começa a atrair a atenção de um alvo reduzindo o seu foco no combate com uma performance artística de sua área de atuação. Através desse movimento o usuário cria uma abertura onde algum de seus aliados pode realizar uma ação de desarmamento ou roubo contra o indivíduo distraído e com isso o indivíduo em questão realizará a rolagem de resistência ao roubo/desarmamento com desvantagem e com um demérito de -10 em seus modificadores. Esse movimento não funciona mais do que uma vez contra o mesmo indivíduo. O uso dessa habilidade consome a ação do Artista." },
            { tier: "TIER_X", title: "Fingir-se de Morto", body: "Através do uso dessa habilidade, o Artista começa a ser capaz de realizar uma performance cênica que captura todos os indivíduos próximos. Esse movimento é utilizado imediatamente após sofrer um golpe, e o Charlatão lança-se contra o chão e finge ter sido eliminado do combate. Ao fazer isso, a próxima ação do Charlatão recebe um bônus de vantagem, seja para fuga ou para surpreender seus inimigos. Esse movimento não funciona mais do que uma vez contra o mesmo indivíduo e outros indivíduos próximos." },
            { tier: "TIER_XX", title: "Fechar as Cortinas", body: "O charlatão utiliza todos seus aprendizados como um artista para realizar o seu último ato — um Último Movimento acompanhado de todos os membros da tripulação do artista. Ao declarar o uso desse movimento, o artista começa a sua performance artística consumindo inteiramente a sua barra de energia. Através do uso dessa habilidade o artista permite que todos os membros de sua tripulação fujam da cena utilizando de uma rolagem com vantagem, enquanto mantém todos inimigos distraídos e focados em sua apresentação. Com o fim das rolagens de seus aliados, o Charlatão atrai a atenção de todos os indivíduos próximos a outro ponto e realiza a sua própria rolagem de fuga com vantagem." },
          ],
        },
      ],
    },
  ],
};
