import type { ProfessionData } from "./types";

export const BIOLOGO: ProfessionData = {
  id: "biologo",
  name: "Biólogo",
  description:
    "Os biólogos são sujeitos que se inclinam à produção de conhecimento acerca de métodos de intervenção em seres vivos, se especializando no cuidado de ferimentos e doenças que afligem as raças humanóides. Os biólogos são os indivíduos mais capacitados em identificar ferimentos e arquitetar planos para tratar tais ferimentos, representando uma figura de valor inestimável para qualquer grupo.\n\nInicialmente, os personagens que seguem este caminho iniciam na profissão Biólogo, e eventualmente podem se especializar e se tornar Médico ou Pesquisador.\n\nCaso se torne um Médico, evolui para o domínio Dominador de Imprevistos ou Minucioso Absoluto.\n\nCaso se torne um Pesquisador, evolui para o domínio Antagonista da Praga ou Explorador Psíquico.",
  initialAbilities: [
    { tier: "INICIAL", title: "Artesão de Remendos", body: "Os biólogos são indivíduos que buscam estender seus conhecimentos acerca das espécies racionais, realizando análises e pesquisas a respeito dos indivíduos, visando entender sua anatomia, comportamento e sanar suas necessidades. Por conta disso, são os únicos capazes de utilizar os Kits Médicos para tratar ferimentos (São limitados a utilizar Kits Médicos de seu Tier atual ou inferior). Enquanto exerce qualquer ação que desencadeia um Teste de Biólogo, o personagem recebe um acréscimo de modificadores de 06 por Tier da profissão (Inicial = 0)." },
    { tier: "TIER_I", title: "Lupa Humana", body: "Alcançando o primeiro nível profissional, o biólogo se torna capaz de realizar uma “Observação Analítica”. Essa observação pode ser utilizada quando o biólogo está diante de um aspecto biológico que deseja entender em um indivíduo, servindo para analisar comportamentos isolados, extensões de ferimentos, efetividade e tempo de propagação de doenças e venenos, e outros. O sucesso da Observação Analítica possui dificuldade estabelecida pelo mestre e determinada pela complexidade do que o biólogo deseja observar, e sua rolagem é referente a um Teste de Biólogo." },
    { tier: "TIER_II", title: "Apertar Sutura", body: "Ao obterem conhecimentos medicinais ainda mais aprofundados, os biólogos são capazes de, a partir desse nível profissional, utilizar os Kits Médicos com maior eficácia, melhorando a regeneração concedida por qualquer tratamento utilizando um Kit Médico em 15%. Além disso, quando o biólogo utiliza a Observação Analítica com o intuito de investigar as extensões de um ferimento e a melhor forma de intervenção medicinal, caso tenha sucesso, ele aumenta o bônus concedido por essa habilidade em mais 15%." },
    { tier: "TIER_III", title: "Inspeção Comportamental", body: "Chegando no auge de sua profissão basal, o biólogo desbrava o campo da pesquisa e foca na aquisição de conhecimentos acerca de comportamentos das raças racionais e dos males que as aflige. Nesse Tier profissional, quando o biólogo realizar uma Observação Analítica com o intuito de obter conhecimentos acerca de motivações comportamentais, tentando buscar respostas a um comportamento analisado, em sucessos, ele receberá uma resposta de nível moderado do mestre, explicando a visão científica do personagem a respeito do comportamento apresentado pelo indivíduo estudado." },
  ],
  specializations: [
    {
      id: "medico",
      name: "Médico",
      description:
        "Os Médicos são biólogos que se aprofundam diretamente na área da intervenção, se especializando no tratamento de ferimentos, utilizando métodos tanto imediatos quanto minuciosos, trazendo o bem estar de seus companheiros a partir de diversas técnicas medicinais.",
      abilities: [
        { tier: "TIER_IV", title: "Juramento de Hipócrates", body: "Ao escolher a especialização Médico, o biólogo se aprofunda no caminho do curandeiro. Adentrando nessa especialidade, o médico recebe a capacidade de, sempre que realizar o uso de uma Observação Analítica para observar a extensão dos ferimentos de seus aliados e suceder, além de ganhar as bonificações referentes à habilidade citada, também receberá a capacidade de realizar sua rolagem do Kit Médico com vantagem." },
        { tier: "TIER_V", title: "Acampamento de Cuidado", body: "Avançando em suas habilidades nesta especialização, o médico se torna capaz de levantar um Acampamento de Cuidado. Para isso, o médico e seu grupo devem possuir um Kit de Acampamento Médico, que custa $150.000.000 e que não é consumido com o uso. Ao montar um Acampamento de Cuidado, o médico se torna capaz de realizar o tratamento emergencial em até 4 indivíduos simultaneamente, substituindo um tratamento rápido para um tratamento longo e contínuo, tratando-os gradualmente durante um período de vinte e quatro horas. Quando tratando indivíduos com o Acampamento de Cuidado, o médico é capaz de utilizar um único Kit Médico para tratar as feridas de dois indivíduos distintos." },
        { tier: "TIER_VI", title: "Sala Branca", body: "Nesse nível profissional, o biólogo se torna capaz de customizar completamente um cômodo de seu navio, ao custo de $350.000.000, criando uma sala de cirurgia dentro do seu navio, que pode ser utilizada para procedimentos minuciosos. Dentro dessa sala, o biólogo possui todos os instrumentos básicos necessários para a maioria dos procedimentos de emergência em corpos humanoides, e sempre que realiza um Teste de Biólogo para tratar um ferimento dentro da Sala de Cirurgia, recebe uma bonificação de +3 de modificadores." },
        { tier: "TIER_VII", title: "Bisturi Milagroso", body: "Alcançando o ápice de suas habilidades como um simples médico, o biólogo torna-se um exímio conhecedor dos corpos de seres racionais. Ao obter essa habilidade, o Médico se torna capaz de adiantar o seu turno em combate para amparar um aliado que recebeu um dano fatal. Ao fazer isso, o médico é capaz de realizar um Teste de Biólogo para tratar o ferimento de forma improvisada e minuciosa, contendo os danos sofridos pelo corpo de seu aliado, reduzindo o que seria uma morte garantida em um coma duradouro. O médico é capaz de manter um indivíduo vivo por até 5 minutos/turnos antes de ser necessário o auxílio de um ambiente propício e equipamentos especializados." },
      ],
      domains: [
        {
          id: "dominador_imprevistos",
          name: "Dominador de Imprevistos",
          description:
            "Os Dominadores de Imprevistos são indivíduos que se especializaram em métodos medicinais e que se aprofundam no domínio de métodos de intervenção imediatos, lidando com ferimentos letais no momento em que acontecem.",
          abilities: [
            { tier: "TIER_VIII", title: "Ciclo da Vida", body: "Ao atingir esse Tier de profissão, o personagem pode consolidar-se no domínio do Dominador de Imprevistos. No momento em que atinge esse Tier, o biólogo recebe a capacidade de conduzir um “Ciclo de Intervenção”. Quando está conduzindo um ciclo, o personagem deverá realizar constantes Testes de Biólogo para controlar as extensões de um ferimento seu ou de algum alvo. Enquanto estiver mantendo um Ciclo de Intervenção, o personagem é incapaz de agir, porém impossibilita que o ferimento que está tratando piore. A cada falha, o ferimento piorará e se estenderá. Por conta desse domínio, o personagem deixa de receber 06 de modificador em Testes de Biólogo por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Analgésico de Zunesha", body: "Conforme avança no domínio de sua profissão, o biólogo se torna capaz de adicionar um novo fármaco em seus Kit Médicos, ao custo de $50.000.000 para cada Kit. Uma vez por batalha, o médico é capaz de realizar um tratamento especial em algum indivíduo com um de seus Kit Médicos especiais, consumindo o Kit para aplicar apenas metade de sua regeneração, mas aplicando o efeito do fármaco: o paciente recebe um potente analgésico, ficando imune à sensação de danos recebidos e com danos reduzidos em 30%. Toda vez que o alvo recebe algum dano o biólogo pode realizar uma rolagem de Teste de Biólogo, e em sucesso reduzirá os danos recebidos em mais 20%." },
            { tier: "TIER_X", title: "Rede de Cuidados", body: "Com esse Tier Profissional, o Dominador de Imprevistos começa a ser capaz de refinar ainda mais suas habilidades, conseguindo manter o cuidado contínuo de um paciente enquanto mantém sua atenção para realizar o tratamento de outros indivíduos. Com essa habilidade, o médico consegue realizar tratamentos especiais em indivíduos que acabaram de se ferir gravemente, aplicando um tratamento imediatista rápido que impede o ferimento de piorar. Ao conseguir fazer uso dessa habilidade com sucesso, o biólogo é capaz de reduzir pela metade os danos adicionais que seriam recebidos pelo paciente ao receber golpes naquela região." },
            { tier: "TIER_XX", title: "Volte por Nós", body: "Atingindo o auge de seu domínio profissional, o biólogo se torna capaz de realizar milagres dentro do campo de batalha. Uma vez durante uma batalha, o Dominador de Imprevistos é capaz de realizar um milagre medicinal — costurar imediatamente um membro perdido, juntar partes ceifadas de um corpo, usar placas de metal para fechar grandes feridas. Com essa habilidade, o biólogo é capaz de reverter danos severos, possibilitando tratar indivíduos considerados mortos que estejam com HP zerado ou até 25% negativado, retornando-o a 1 de HP em um estado de consciência levemente rebaixada. O uso dessa habilidade consome inteiramente o turno do biólogo." },
          ],
        },
        {
          id: "minucioso_absoluto",
          name: "Minucioso Absoluto",
          description:
            "Os Minuciosos Absolutos são indivíduos que se aprofundaram no campo dos tratamentos médicos e se especializaram no domínio de métodos de intervenção e cuidado complexos e minuciosos, capazes de tratar ferimentos internos com extrema maestria.",
          abilities: [
            { tier: "TIER_VIII", title: "Ciclo da Vida", body: "Ao atingir esse Tier de profissão, o personagem pode consolidar-se no domínio do Minucioso Absoluto. No momento em que atinge esse Tier, o biólogo recebe a capacidade de conduzir um “Ciclo de Intervenção”: um processo cirúrgico em seu paciente, necessitando utilizar uma sala de cirurgia devidamente equipada. Enquanto mantém o Ciclo, o biólogo é capaz de intervir em ferimentos internos, realizando constantes Testes de Biólogo — a cada sucesso trata parte dos danos internos, tendo uma piora a cada falha. Por conta desse domínio, o personagem deixa de receber 06 de modificador em Testes de Biólogo por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Combatentes não Visíveis", body: "Alcançando esse nível profissional, o biólogo se torna capaz de iniciar uma pesquisa aprofundada sobre anticorpos, conseguindo desenvolver sua primeira remessa de anticorpos artificiais. O biólogo é capaz de implantar esses anticorpos em indivíduos específicos pelo custo de $100.000.000 para cada remessa. Indivíduos que estejam com os anticorpos presentes em seu organismo são capazes de reduzir pela metade a duração de qualquer doença ou envenenamento, contudo, os anticorpos são rejeitados após 2 meses ingame." },
            { tier: "TIER_X", title: "Besta da Sala Branca", body: "Sempre que o Minucioso Absoluto realizar um Ciclo de Intervenção em uma Sala Cirúrgica, ele realizará todos os Testes de Biólogo com vantagem. Além disso, sua pesquisa sobre os anticorpos avança ainda mais, alcançando uma potência que possibilita que indivíduos que possuam os anticorpos tornem-se muito mais resistentes a qualquer tipo de envenenamento ou infecções, recebendo apenas 50% dos danos e efeitos adversos. A duração dos anticorpos também é aumentada, passando a integrar o corpo do indivíduo por até um ano." },
            { tier: "TIER_XX", title: "Toque Milagroso", body: "Atingindo o auge de sua profissão, o biólogo se torna capaz de realizar uma grande pesquisa para destrinchar os segredos das Células Tronco. Ao custo de $500.000.000 e três meses de estudo, o biólogo se torna capaz de realizar cirurgias com Células Tronco. Com essa habilidade, o Minucioso Absoluto é capaz de realizar transplantes de Células Tronco de embriões em seres humanos desenvolvidos, possibilitando uma taxa de regeneração anormal para fazer com que membros perdidos sejam regenerados e feridas ou doenças incuráveis comecem a ser regeneradas." },
          ],
        },
      ],
    },
    {
      id: "pesquisador",
      name: "Pesquisador",
      description:
        "Os Pesquisadores são biólogos que se dedicam na área da produção de conhecimentos, realizando pesquisas distintas para adquirir conhecimentos acerca de temas que julgam necessários.",
      abilities: [
        { tier: "TIER_IV", title: "Pesquisa Exploratória", body: "Ao escolher a especialização Pesquisador, o biólogo deixa de desenvolver suas capacidades de intervenção direta para se aprofundar no campo da pesquisa. O Pesquisador deverá escolher um campo para iniciar uma pesquisa exploratória. Após a aquisição dessa habilidade, o Biólogo é capaz de realizar uma rolagem de 1d6 por sessão, obtendo % equivalente ao resultado alcançado como progresso de sua pesquisa atual. Toda vez que a pesquisa é completa, o Biólogo recebe uma nova informação inovadora acerca do tema estudado. Uma mesma pesquisa só pode ser completa 3 vezes." },
        { tier: "TIER_V", title: "Pesquisa Quantitativa", body: "O Pesquisador passa a ser capaz de evoluir sua pesquisa para um teor mais quantitativo. É necessário que a pesquisa atual já tenha sido completada 3 vezes. Inicia-se o processo de estudo quantitativo, onde o biólogo interage diretamente com o foco de sua pesquisa. A cada interação direta deve-se realizar um Teste de Biólogo com Dificuldade 43, e em sucessos, se obtém um acúmulo de dados quantitativos. Ao obter dez acúmulos, esse tipo de pesquisa está completo. O Pesquisador só é capaz de obter um acúmulo por sessão." },
        { tier: "TIER_VI", title: "Estagiário Remunerado", body: "O Pesquisador torna-se capaz de contratar um NPC aprendiz de pesquisador, devendo pagar um salário de $25.000.000 mensais. Com isso, o biólogo é capaz de dobrar o número de rolagens de sua pesquisa exploratória por sessão, e possibilita o ganho de duas vezes mais dados quantitativos obtidos por sessão." },
        { tier: "TIER_VII", title: "Farmacologia Improvisada", body: "O Pesquisador é capaz de começar a desenvolver intervenções diretas. Torna-se possível ao biólogo conseguir realizar a criação de fármacos capazes de retardar ou até mesmo curar completamente certas doenças. Para isso, o biólogo precisa ter completado três vezes uma pesquisa acerca da doença. Inicialmente o fármaco reduz o tempo de atuação; após uma pesquisa quantitativa, reduz os sintomas; após três pesquisas quantitativas, alcança a cura total. Essa habilidade só pode ser utilizada para desenvolver fármacos contra doenças “comuns” e “raras”." },
      ],
      domains: [
        {
          id: "antagonista_praga",
          name: "Antagonista da Praga",
          description:
            "Os Antagonistas da Praga são biólogos que se especializam na produção de conhecimento a partir de pesquisas e adentram o domínio da identificação e tratamento de doenças.",
          abilities: [
            { tier: "TIER_VIII", title: "Médico das Pragas", body: "A partir desse nível profissional, o biólogo começa a ter um conhecimento basal acerca de todas as doenças não psicológicas conhecidas. Torna-se possível a realização de Testes de Biólogo para desvendar que tipo de doença está afetando algum indivíduo. O biólogo passa a ter conhecimento basal para tratar qualquer tipo de doença considerada “comum”. Por conta desse domínio, o personagem deixa de receber 06 de modificador em Testes de Biólogo por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Métodos Invasivos", body: "O biólogo aprimora “Farmacologia Improvisada” para também ser capaz de criar fármacos contra doenças não psicológicas “extremamente raras”. O biólogo passa a ter conhecimento basal para tratar qualquer tipo de doença considerada “rara”." },
            { tier: "TIER_X", title: "Redenção do Antagonista", body: "O biólogo se torna capaz de começar a desenvolver doenças de maneira controlada. É necessário possuir um laboratório e consumir $350.000.000. O biólogo é capaz de criar substâncias que infectam indivíduos com doenças a partir do toque ou consumo. Para criar uma dessas substâncias, o biólogo precisa possuir conhecimento acerca de tal doença. O biólogo passa a ter conhecimento basal para tratar qualquer tipo de doença considerada “extremamente rara”." },
            { tier: "TIER_XX", title: "O Verdadeiro Antagonista", body: "O biólogo é capaz de realizar alterações em seu laboratório de pesquisa pelo custo de $750.000.000. Com essa habilidade, o biólogo se torna capaz de realizar uma pesquisa aprofundada acerca de uma doença que estudou e desenvolver formas de alterar seu comportamento, criando uma mutação da patologia estudada, uma enfermidade feita artificialmente. Para realizar as alterações, o biólogo necessita investir um ano de estudos. O biólogo se torna capaz de identificar e criar fármacos que visem tratar doenças não psicológicas de grau superior a “extremamente raras”." },
          ],
        },
        {
          id: "explorador_psiquico",
          name: "Explorador Psíquico",
          description:
            "Os Exploradores Psíquicos são indivíduos que se aprofundaram no campo da pesquisa e se especializaram no domínio da produção de conhecimento acerca dos comportamentos das espécies, capazes de tratar transtornos psicológicos.",
          abilities: [
            { tier: "TIER_VIII", title: "Sessão de Terapia", body: "O Explorador Psíquico começa a ser capaz de induzir indivíduos a sessões exaustivas de exploração mental, utilizando a hipnose como principal meio de investigação. O biólogo deverá iniciar uma Pesquisa Exploratória para cada paciente. Com a conclusão da pesquisa, o biólogo consegue ter uma visão ampla do estado psicológico de seu paciente. O biólogo passa a ter conhecimento basal para tratar qualquer tipo de doença psicológica considerada “comum”. Por conta desse domínio, o personagem deixa de receber 06 de modificador em Testes de Biólogo por Tier de profissão e passa a receber 07 de modificador por Tier de profissão." },
            { tier: "TIER_IX", title: "Métodos Invasivos", body: "O biólogo aprimora “Farmacologia Improvisada” para também ser capaz de criar fármacos com o intuito de tratar doenças psicológicas “extremamente raras”. O biólogo passa a ter conhecimento basal para tratar qualquer tipo de doença psicológica considerada “rara”." },
            { tier: "TIER_X", title: "Memórias Recalcadas", body: "Necessitando de um laboratório e $350.000.000, o Explorador Psíquico começa a desenvolver métodos de controle mental, conseguindo realizar alterações temporárias ou permanentes no modo de pensar de seus pacientes. Após três Pesquisas Exploratórias sobre a mente do indivíduo, o biólogo se torna capaz de determinar quais memórias serão inacessíveis e quais serão acessíveis, alterando levemente parte das memórias observadas. O biólogo passa a tratar qualquer tipo de doença psicológica “extremamente rara”." },
            { tier: "TIER_XX", title: "Leitura Comportamental", body: "Com essa habilidade, sempre que um indivíduo realizar qualquer tipo de ação, o Explorador Psíquico receberá uma bonificação de +3 de Modificador para reagir àquela ação. Caso o biólogo tenha concluído uma Pesquisa Exploratória acerca da mente do indivíduo, além da bonificação, também recebe vantagem em qualquer rolagem que vise reagir a uma ação feita por seu antigo paciente. Atingindo esse nível profissional, o biólogo se torna capaz de criar fármacos para tratar doenças psicológicas de grau superior a “extremamente raras”." },
          ],
        },
      ],
    },
  ],
};
